### ISSUE TITLE
when receiving call from part-up/discover fetch recommended part-up id's

### ISSUE THREAD

**Issue by ralphboeije** [part-up/api#13]
Extra description needed @vanderGoes

**Comment by jplattel** [comment]
This branch: https://github.com/part-up/part-up/tree/feat-discover-recommendations is now using the sort paramater with 'recommended' as value to query the API. You can use this to test the API results.

**Comment by wouterd** [comment]
# Recommended Partups - Discover Page

Name of feature branch: feat-discover-recommendations

## Frontend Meteor
- Extra filter: recommended
- Request to Meteor API with different sort param (relevance)
- New default “discover mode”
- Add CTA to “newest” Part-ups

## Backend Meteor
 - Implement sorting by relevance:
	- Call the Partup API (api.part-up.com) for X recommended part-ups (IDs)
	- Create the objects that the fronted expects (same as other sorting)

## Part-up API (api.part-up.com)
- Implement endpoint that gives recommended partups for a user
	- Input: userId, via url, encrypted with shared secret (api key) => AES, Base64UrlEncoded
	- Output: Partup IDs, sorted by relevance (List)
```
{
	partUpIds: [“18u2ejdlfas”, “9283urfdsalfjasl”]
}
```
	- Calling Principal: “Trusted System” 
	- URL: https://api.part-up.com/partups/recommended/for/user/{userId}

- Create Neo4J Query that grabs X recommended part-up IDs from Neo4J.

## Road to Production
- Package Neo with Recommendation Engine
	- Based Neo docker image
	- include graph aware runtime + reach
	- include recommendation JAR (UBCF)
	- update neo4j.properties
- Deploy Neo on AWS
- Neo + Api + Meteor runnable @local 
- Event processing test
	- Archived partups
	- Fix some properties
- Load test
- Latency test
- Resilience test
- Run an import

**Comment by vanderGoes** [comment]
@wouterd This evening Andrei and I discussed what we have been working on last week. We agreed that is not perfect, but good enough for the next step of setting up an Neo4j with GraphAware that can be read from the API. To test it before we polish it or add extra features.

The function to retrieve the recommendation team ID's is currently included in the UpdateNeo4jActor. Indeed not beautiful, but it does the trick. Anything to add @asomov?

About the 7th-inning-stretch branch: The API now correctly creates the network with all necessary information. However, not all properties of the edges are updated correctly. I e-mailed Wolfgang about that. If I can't fix it, then I'll comment that out. For the user-based collaborative filtering algorithms we don't need those anyway. A pull-request is coming up before Friday :)

We have also checked out  `Array(user_id): _*` which results in [user_id] instead of the string. The positive side is that we do this consistently. Negative, the importer does not and it's ugly. Maybe it is a bug in the JCypher library. I ask Wolfgang that next Tuesday.

I also explained to Andrei that this implementation is cool, but not part of my research. And that in the next weeks I need to focus on finalizing my thesis. Refactoring to JCypher took quite some time last week. After fixing the properties I will scale back and focus.

Most important: How do you feel about taking this next step?

**Comment by vanderGoes** [comment]
@wouterd And this one can be closed too?

**Comment by wouterd** [comment]
Yep!
